Add an example of ESIP Science-On-Schema markup to the data directory.
schemaorg/schemaorg pull request #3065
Opened 2022-03-11 20:51 UTC by nein09

These are examples for scientific research data sets and data repositories taken from the [guide](https://github.com/ESIPFed/science-on-schema.org/tree/master/guides) developed by the Science-On-Schema ESIP cluster.

I'm happy to try and make up HTML / RDFA / other markup for these, but this working group has been focused on JSON-LD.

2022-03-14 23:31 UTC, nein09 commented
@chrisspradling1980 are you talking about this change specifically? I removed the prov elements from the json-ld markup that I am proposing with this pull request because I thought they may be outside the scope of what the schema.org maintainers would like to see in these examples.

2022-04-10 02:39 UTC, chrisspradling1980 commented
I was just do the familiarities of NLP or owl programming language that is persistent inside of GitHub. I know that there are repository containers that store chronological to numeric word cabinets. if we could just eliminate terminology that may pertain to programming language as opposed to everyday usage words that may come conflict with some of the NLP understanding I think this would help scientists and the open source community.
 you have to forgive me I'm not

2022-04-10 02:48 UTC, chrisspradling1980 approved these changes
this looks fine however, if there's any way that we could get data sets to challenge the discrepancy or to find discrepancies to include challenges which would create markup to markdown work overs. then multiple data sets can be challenged for multi language discrepancies in scientific fields and also in computer science for data sets. I hope this wouldn't be too hard or too much to ask but this is important.

2022-04-10 02:48 UTC, chrisspradling1980 commented on data/sdo-soso-dataset-examples.txt
> +TODO
Find and define all terminology discrepancies between all compilers, programming languages, markup, mark down, data sets and computational linguistic systems containers and or libraries as repositories for owl, RTL and xbrtl file formats.

2022-04-13 19:05 UTC, smrgeoinfo commented on data/sdo-soso-dataset-examples.txt
> +TODO
What is the point of this comment?

2022-10-04 19:32 UTC, RichardWallis requested changes
Some fixes required after [validating](https://validator.schema.org/) :

**First example**

1.  Misspelling of 'application' in script tag
2. Extra comma at end of description

**Second example**

1. No TYPES: definition
2. availableChannel not a valid property for Organization type

2022-10-05 23:05 UTC, nein09 commented
@RichardWallis thank you! I thought I had run it through a validator but I guess I hadn't, or at least not the right one.

2023-04-06 15:10 UTC, RichardWallis approved these changes

2023-04-06 15:14 UTC, merged