Add codespell: config + workflow (to catch new typos) + fix a number of typos using codespell
schemaorg/schemaorg pull request #3474
Opened 2024-03-01 21:19 UTC by yarikoptic

Initially encountered typos in another representation of past version of linkml elsewhere, decided to fix them "in the root" ;)   more on codespell: https://github.com/codespell-project/codespell . Resulted in fixing some code including 1 interface but IMHO was ok.

2024-03-06 12:04 UTC, MatthiasWiesmann requested changes

2024-03-06 12:04 UTC, MatthiasWiesmann commented on data/ext/health-lifesci/med-health-core.ttl
I don't think this fix is correct:

- reoccurrence = a further or repeated occurrence. 
- recurrence = the fact of occurring again.

2024-03-06 20:29 UTC, yarikoptic commented on data/ext/health-lifesci/med-health-core.ttl
thanks for spotting!

Filed
- https://github.com/codespell-project/codespell/pull/3378
to address "upstream". 

Redid fixing, force-pushed.

2024-03-07 08:38 UTC, MatthiasWiesmann approved these changes

2024-05-13 12:23 UTC, merged